import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const blankProduct={name:"",code:"",category:"Espetos",description:"",image_url:"",cost:0,price:0,stock:0,min_stock:10,unit:"un",sector:"Churrasqueira",printer:"Nenhuma",track_stock:true,active:true};

function App(){
 const[session,setSession]=useState(null),[user,setUser]=useState("admin"),[pass,setPass]=useState("1234"),[page,setPage]=useState("dashboard"),[data,setData]=useState({}),[error,setError]=useState("");
 const api=async(path,opt={})=>{const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.token}`}:{})},...opt});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.detail||"Erro ao processar");return j};
 const load=async()=>{if(!session)return;try{const a=await Promise.all([api("/products"),api("/tables"),api("/production"),api("/customers"),api("/reservations")]);const n={products:a[0],tables:a[1],production:a[2],customers:a[3],reservations:a[4]};if(session.role==="admin"){const x=await Promise.all([api("/dashboard"),api("/expenses"),api("/audit")]);n.dashboard=x[0];n.expenses=x[1];n.audit=x[2]}setData(n)}catch(e){setError(e.message)}};
 useEffect(()=>{if(session)load()},[session]);
 const login=async()=>{try{setError("");const s=await api("/auth/login",{method:"POST",body:JSON.stringify({username:user,password:pass})});setSession(s);setPage(s.role==="admin"?"dashboard":"tables")}catch(e){setError(e.message)}};
 const request=async(path,opt={})=>{try{setError("");const out=await api(path,opt);await load();return out}catch(e){setError(e.message);throw e}};
 if(!session)return <div className="login"><div className="loginCard"><div className="logo">R</div><h1>REI'SPETOS OS</h1><p>Gestão operacional</p><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Usuário"/><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Senha" onKeyDown={e=>e.key==="Enter"&&login()}/><button onClick={login}>Entrar</button>{error&&<div className="error">{error}</div>}<small>admin / 1234<br/>caixa / 0000</small></div></div>;
 const admin=session.role==="admin";const menu=admin?["dashboard","products","tables","production","customers","reservations","expenses","audit"]:["tables","production","customers","reservations"];
 const names={dashboard:"Dashboard",products:"Produtos",tables:"Mesas e Comandas",production:"Produção",customers:"Clientes",reservations:"Reservas",expenses:"Despesas",audit:"Auditoria"};
 return <div className="app"><aside><div className="brand"><div className="mini">R</div><div><b>REI'SPETOS</b><span>{admin?"Admin / Dono":"Caixa"}</span></div></div><nav>{menu.map(m=><button key={m} className={page===m?"active":""} onClick={()=>setPage(m)}>{names[m]}</button>)}</nav><button className="danger" onClick={()=>setSession(null)}>Sair</button></aside><main><div className="pageHead"><div><h1>{names[page]}</h1><p>Sistema REI'SPETOS</p></div></div>{error&&<div className="error">{error}</div>}{page==="dashboard"&&admin&&<Dashboard d={data.dashboard}/>} {page==="products"&&admin&&<Products products={data.products||[]} request={request}/>} {page==="tables"&&<Tables tables={data.tables||[]} products={(data.products||[]).filter(x=>x.active)} request={request}/>} {page==="production"&&<Production items={data.production||[]} request={request}/>} {page==="customers"&&<Customers items={data.customers||[]} request={request}/>} {page==="reservations"&&<Reservations items={data.reservations||[]} request={request}/>} {page==="expenses"&&admin&&<Expenses items={data.expenses||[]} request={request}/>} {page==="audit"&&admin&&<Audit items={data.audit||[]}/>}</main></div>
}

const Dashboard=({d})=>d?<><div className="cards"><div className="card"><span>Faturamento</span><b>{money(d.revenue)}</b></div><div className="card"><span>Lucro estimado</span><b>{money(d.profit)}</b></div><div className="card"><span>Mesas abertas</span><b>{d.open_tables}</b></div><div className="card"><span>Estoque crítico</span><b>{d.low_stock}</b></div></div><div className="panel welcome"><h2>Operação pronta</h2><p>Cadastre produtos com custo, margem, setor de produção e estoque mínimo. O próximo módulo será Mesas e Comandas individuais.</p></div></>:null;

function Products({products,request}){
 const[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blankProduct),[search,setSearch]=useState(""),[category,setCategory]=useState("Todos"),[stockModal,setStockModal]=useState(null),[stockForm,setStockForm]=useState({qty:0,movement_type:"entry",note:""});
 const cats=useMemo(()=>["Todos",...new Set(products.map(p=>p.category||"Outros"))],[products]);
 const shown=products.filter(p=>(category==="Todos"||(p.category||"Outros")===category)&&(`${p.name} ${p.code||""}`.toLowerCase().includes(search.toLowerCase())));
 const startNew=()=>{setEditing(null);setForm(blankProduct);setOpen(true)};
 const startEdit=p=>{setEditing(p);setForm({...blankProduct,...p});setOpen(true)};
 const save=async()=>{const opt={method:editing?"PUT":"POST",body:JSON.stringify({...form,cost:+form.cost,price:+form.price,stock:+form.stock,min_stock:+form.min_stock})};await request(editing?`/products/${editing.id}`:"/products",opt);setOpen(false)};
 const deactivate=async p=>{if(confirm(`Desativar ${p.name}?`))await request(`/products/${p.id}`,{method:"DELETE"})};
 const adjust=async()=>{await request(`/products/${stockModal.id}/stock`,{method:"POST",body:JSON.stringify({...stockForm,qty:+stockForm.qty})});setStockModal(null);setStockForm({qty:0,movement_type:"entry",note:""})};
 const active=products.filter(p=>p.active).length,critical=products.filter(p=>p.active&&p.track_stock&&p.stock<=p.min_stock).length,totalValue=products.reduce((s,p)=>s+(p.active?p.stock*p.cost:0),0);
 return <>
  <div className="cards productStats"><div className="card"><span>Produtos ativos</span><b>{active}</b></div><div className="card"><span>Estoque crítico</span><b>{critical}</b></div><div className="card"><span>Valor em estoque</span><b>{money(totalValue)}</b></div><div className="card actionCard"><button onClick={startNew}>+ Novo produto</button></div></div>
  <div className="toolbar"><input placeholder="Buscar produto ou código" value={search} onChange={e=>setSearch(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="productGrid">{shown.map(p=>{const profit=p.price-p.cost,margin=p.cost?profit/p.cost*100:0;const critical=p.track_stock&&p.stock<=p.min_stock;return <article className={`productCard ${!p.active?"inactive":""}`} key={p.id}><div className="productTop"><div className="productImage">{p.image_url?<img src={p.image_url}/>:<span>{p.name.slice(0,1).toUpperCase()}</span>}</div><div><span className="pill">{p.category||"Outros"}</span><h3>{p.name}</h3><small>{p.code||`PROD-${String(p.id).padStart(4,"0")}`}</small></div></div><div className="priceRow"><div><span>Custo</span><b>{money(p.cost)}</b></div><div><span>Venda</span><b>{money(p.price)}</b></div><div><span>Lucro</span><b>{money(profit)}</b></div><div><span>Margem</span><b>{margin.toFixed(1)}%</b></div></div><div className="stockBox"><div><span>Estoque</span><b className={critical?"critical":""}>{p.track_stock?`${p.stock} ${p.unit||"un"}`:"Não controlado"}</b></div><small>Mínimo: {p.min_stock} {p.unit||"un"}</small></div><div className="meta"><span>Produção: <b>{p.sector}</b></span><span>Impressão: <b>{p.printer||"Nenhuma"}</b></span></div><div className="cardActions"><button className="secondary" onClick={()=>startEdit(p)}>Editar</button><button className="secondary" onClick={()=>{setStockModal(p);setStockForm({qty:0,movement_type:"entry",note:""})}}>Estoque</button>{p.active&&<button className="ghostDanger" onClick={()=>deactivate(p)}>Desativar</button>}</div></article>})}</div>
  {open&&<Modal title={editing?"Editar produto":"Novo produto"} close={()=>setOpen(false)}><ProductForm form={form} setForm={setForm}/><div className="modalActions"><button className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button onClick={save}>Salvar produto</button></div></Modal>}
  {stockModal&&<Modal title={`Ajustar estoque — ${stockModal.name}`} close={()=>setStockModal(null)}><div className="formGrid"><label>Quantidade (+ entrada / - saída)<input type="number" value={stockForm.qty} onChange={e=>setStockForm({...stockForm,qty:e.target.value})}/></label><label>Tipo<select value={stockForm.movement_type} onChange={e=>setStockForm({...stockForm,movement_type:e.target.value})}><option value="entry">Entrada</option><option value="loss">Perda</option><option value="adjustment">Ajuste</option><option value="return">Devolução</option></select></label><label className="full">Observação<input value={stockForm.note} onChange={e=>setStockForm({...stockForm,note:e.target.value})} placeholder="Ex.: compra do fornecedor"/></label></div><div className="modalActions"><button className="secondary" onClick={()=>setStockModal(null)}>Cancelar</button><button onClick={adjust}>Confirmar ajuste</button></div></Modal>}
 </>
}

function ProductForm({form,setForm}){const set=(k,v)=>setForm({...form,[k]:v});return <div className="formGrid"><label>Nome do produto<input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Ex.: Espeto de carne"/></label><label>Código interno<input value={form.code||""} onChange={e=>set("code",e.target.value)} placeholder="ESP-CARNE"/></label><label>Categoria<select value={form.category} onChange={e=>set("category",e.target.value)}><option>Espetos</option><option>Cervejas</option><option>Chopp</option><option>Refrigerantes</option><option>Porções</option><option>Drinks</option><option>Sobremesas</option><option>Outros</option></select></label><label>Setor de produção<select value={form.sector} onChange={e=>set("sector",e.target.value)}><option>Churrasqueira</option><option>Bar</option><option>Cozinha</option><option>Fritadeira</option><option>Sem produção</option></select></label><label>Custo<input type="number" step="0.01" value={form.cost} onChange={e=>set("cost",e.target.value)}/></label><label>Preço de venda<input type="number" step="0.01" value={form.price} onChange={e=>set("price",e.target.value)}/></label><label>Estoque atual<input type="number" step="0.01" value={form.stock} onChange={e=>set("stock",e.target.value)}/></label><label>Estoque mínimo<input type="number" step="0.01" value={form.min_stock} onChange={e=>set("min_stock",e.target.value)}/></label><label>Unidade<select value={form.unit} onChange={e=>set("unit",e.target.value)}><option value="un">un</option><option value="espeto">espeto</option><option value="garrafa">garrafa</option><option value="copo">copo</option><option value="porção">porção</option><option value="kg">kg</option><option value="litro">litro</option></select></label><label>Impressora<select value={form.printer} onChange={e=>set("printer",e.target.value)}><option>Nenhuma</option><option>Churrasqueira</option><option>Bar</option><option>Cozinha</option></select></label><label className="full">URL da foto<input value={form.image_url||""} onChange={e=>set("image_url",e.target.value)} placeholder="https://..."/></label><label className="full">Descrição<textarea value={form.description||""} onChange={e=>set("description",e.target.value)} placeholder="Descrição opcional"/></label><label className="check"><input type="checkbox" checked={form.track_stock} onChange={e=>set("track_stock",e.target.checked)}/> Controlar estoque</label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/> Produto ativo</label></div>}
const Modal=({title,close,children})=><div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={close}>×</button></div>{children}</div></div>;

function Tables({tables,products,request}){const[n,setN]=useState("Mesa 01"),[c,setC]=useState("");return <><div className="panel"><div className="form"><input value={n} onChange={e=>setN(e.target.value)}/><input placeholder="Cliente" value={c} onChange={e=>setC(e.target.value)}/><button onClick={()=>request("/tables",{method:"POST",body:JSON.stringify({name:n,customer_name:c})})}>Abrir mesa</button></div></div>{tables.map(t=><TableCard key={t.id} t={t} products={products} request={request}/>)}</>}
function TableCard({t,products,request}){const[p,setP]=useState(products[0]?.id||""),[q,setQ]=useState(1);useEffect(()=>{if(!p&&products[0])setP(products[0].id)},[products]);return <div className="panel"><div className="line"><div><b>{t.name}</b><div>{t.customer_name}</div></div><div className="big">{money(t.total)}</div></div><div className="form"><select value={p} onChange={e=>setP(e.target.value)}>{products.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input type="number" value={q} onChange={e=>setQ(+e.target.value)}/><button onClick={()=>request(`/tables/${t.id}/items`,{method:"POST",body:JSON.stringify({product_id:+p,qty:q,note:""})})}>Adicionar</button></div>{t.items.map(i=><div className="item" key={i.id}>{i.qty}x {i.product_name} — {i.status}</div>)}<button className="secondary" onClick={()=>request(`/tables/${t.id}/close`,{method:"POST",body:JSON.stringify({payment_method:"Pix"})})}>Fechar em Pix</button></div>}
function Production({items,request}){return <div className="grid2">{["Bar","Churrasqueira","Cozinha","Fritadeira"].map(s=><div className="panel" key={s}><h3>{s}</h3>{items.filter(i=>i.sector===s).map(i=><div className="item" key={i.id}><b>{i.product_name}</b><div>{i.qty}x — {i.status}</div><button onClick={()=>request(`/production/${i.id}/${i.status==="waiting"?"preparing":i.status==="preparing"?"ready":"delivered"}`,{method:"POST",body:"{}"})}>{i.status==="waiting"?"Iniciar":i.status==="preparing"?"Pronto":"Entregue"}</button></div>)}</div>)}</div>}
function Customers({items,request}){const[n,setN]=useState(""),[p,setP]=useState("");return <><div className="panel form"><input placeholder="Nome" value={n} onChange={e=>setN(e.target.value)}/><input placeholder="Telefone" value={p} onChange={e=>setP(e.target.value)}/><button onClick={()=>request("/customers",{method:"POST",body:JSON.stringify({name:n,phone:p})})}>Cadastrar</button></div><div className="panel">{items.map(c=><div className="item" key={c.id}><b>{c.name}</b><div>{c.phone}</div></div>)}</div></>}
function Reservations({items,request}){const[f,setF]=useState({customer_name:"",phone:"",date:"",time:"",people:2,table_name:"Mesa 01"});return <><div className="panel formGrid"><input placeholder="Cliente" onChange={e=>setF({...f,customer_name:e.target.value})}/><input placeholder="Telefone" onChange={e=>setF({...f,phone:e.target.value})}/><input type="date" onChange={e=>setF({...f,date:e.target.value})}/><input type="time" onChange={e=>setF({...f,time:e.target.value})}/><button onClick={()=>request("/reservations",{method:"POST",body:JSON.stringify(f)})}>Reservar</button></div><div className="panel">{items.map(r=><div className="item" key={r.id}><b>{r.customer_name}</b><div>{r.date} {r.time} — {r.people} pessoas</div></div>)}</div></>}
function Expenses({items,request}){const[f,setF]=useState({description:"",category:"Outros",amount:0,status:"pending"});return <><div className="panel form"><input placeholder="Descrição" onChange={e=>setF({...f,description:e.target.value})}/><input type="number" placeholder="Valor" onChange={e=>setF({...f,amount:+e.target.value})}/><button onClick={()=>request("/expenses",{method:"POST",body:JSON.stringify(f)})}>Cadastrar</button></div><div className="panel">{items.map(x=><div className="item" key={x.id}><b>{x.description}</b><div>{money(x.amount)} — {x.status}</div></div>)}</div></>}
const Audit=({items})=><div className="panel">{items.map(x=><div className="item" key={x.id}><b>{x.action}</b><div>{x.username} — {x.detail}</div></div>)}</div>;
createRoot(document.getElementById("root")).render(<App/>);
